apiVersion: v1
kind: ServiceAccount
metadata:
  name: efs-provisioner
  labels:
    app: {{ template "efs-provisioner.name" . }}
    chart: {{ template "efs-provisioner.chartname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
